//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoviesList()
        {
            this.MovieRatings = new HashSet<MovieRating>();
        }
    
        public long MovieId { get; set; }
        public string Title { get; set; }
        public Nullable<int> YearOfRelease { get; set; }
        public byte runningTimeInMinutes { get; set; }
        public string Genres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieRating> MovieRatings { get; set; }
    }
}
